const knex = require("knex")({
  client: "mysql2",
  connection: {
    host: "127.0.0.1",
    user: "root",
    password: "Start1234%",
    database: "idea"
  }
});
const fetch = require("node-fetch");
const http = require('http');
const https = require('https');
const httpAgent = new http.Agent({ keepAlive: true });
const httpsAgent = new https.Agent({ keepAlive: true });
const agent = (_parsedURL) => _parsedURL.protocol == 'http:' ? httpAgent : httpsAgent;
const FormData = require('form-data');

async function getBooks(page = 0) {
  var formdata = new FormData();
  //generated by postman
  formdata.append("prt", "INTERNET");
  formdata.append("var", "portal");
  formdata.append("vestnr", "9996");
  formdata.append("fmt", "json");
  formdata.append("search_in", "iets");
  formdata.append("amount", "30");
  formdata.append("catalog", "default");
  formdata.append("event", "osearch");
  formdata.append("preset", "all");
  formdata.append("offset", page * 30);
  formdata.append("wf_medium_srt", "BOE");
  formdata.append("wf_karakter", "NJ");
  formdata.append("wf_taal", "DUT");
  formdata.append("wf_genre_rub", "SF");
  formdata.append("qs", "*");
  formdata.append("vcgrpf", "0");
  formdata.append("backend", "wise");
  formdata.append("vcgrpt", "0");

  var requestOptions = {
    method: 'POST',
    body: formdata,
    redirect: 'follow',
    agent
  };

  const response = await fetch("https://webcat.hostedwise.nl/cgi-bin/bx.pl", requestOptions);
  const data = await response.json();

  //Remap json
  return remapData(data);
}

function remapData(data){
  const mapping = {
    id: "id",
    author: "auteur",
    title: "titel",
    description: "tt_info",
    reeks: "reeks_serie",
    reeks_nr: "reeks_serie_nr",
    pubjaar: "pubjaar",
    detail_url: "detail_uri"
  };

  return data.objects.map(({ fields }) => {
    return Object.entries(mapping).reduce((newObject, [newKey, oldKey]) => {
      if(fields[oldKey]){
        let { content } = fields[oldKey];
        if(!Array.isArray(content)){
          newObject[newKey] = content.value || content.label;
        }else if(content.length > 0){
          if(newKey === "reeks_nr"){
            newObject[newKey] = findSerieNr(content[0].value);
          }else{
            newObject[newKey] = content[0].value;
          }
        }
      }
      return newObject;
    }, {});
  });
}

function findSerieNr(str){
  str = str.toLowerCase();
  //first dutch numbers
  const dutchNumbers = ["eerste", "tweede", "derde", "vierde", "vijfde", "zesde", "zevende", "achtste", "negende", "tiende", "elfde", "twaalfde", "dertiende", "veertiende", "vijftiende"];
  const dutchResult = dutchNumbers.findIndex(dutchNumber => str.includes(dutchNumber));
  if(dutchResult > -1){
    return dutchResult + 1;
  }

  //then split
  const splitResult = str.split(".");
  if(splitResult.length > 1 && splitResult[1].length > 0){
    str = new String(splitResult[1]).trim();
  }

  //Try regex
  const regexResult = str.match(/\d+/);
  if(regexResult){
    return regexResult[0];
  }
  //Try roman numerals
  var format = /^[ivx]+/;
  if(format.test(str)){
    return romanToInt(str);
  }

  //Special cases
  const mapping = {
    "les één": 1,
    "deel i": 1
  }

  if(mapping[str]){
    return mapping[str];
  }

  console.log("Could not find serie nr for " + str);
  return;
}

async function sync(){
  for(var i = 0; i < 41; i++){
    const books = await getBooks(i);
    await knex("books").insert(books).onConflict("id").merge();
    console.log("Done " + i);
    //sleep
    await new Promise(resolve => setTimeout(resolve, 1000));
  }
}

function main(){
  sync();
}

function romanToInt(str){
  var roman = {
    i: 1,
    v: 5,
    x: 10
  }
  var result = 0;
  for(var i = 0; i < str.length; i++){
    var current = roman[str[i]];
    var next = roman[str[i+1]];
    if(current < next){
      result -= current;
    }else{
      result += current;
    }
  }

  if(isNaN(result)){
    console.log("Could not convert " + str);
  }

  return result;
}

main();